# Note there is an oustanding issue with PRs with more than 30 commits
PR_TITLE_REGEX: /(fix|feat|feat!)(:)(.*)/
COMMIT_MESSAGE_REGEX: /(build|chore|ci|docs|feat|feat!|fix|improvement|perf|refactor|revert|style|test)(:)(.*)/
