name: Branch Name Convention Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Branch name rules
        uses: deepakputhraya/action-branch-name@v1.0.0
        with:
          regex: '(([A-Z]+-\d+-(HOTFIX:)?.+)|(RELEASE\/\d{4}\.\d\.\d+)(:.+)?)' # mandatory JIRA ticket # + optional 'HOTFIX:' + summary description OR a release version
          ignore: master,main
          max_length: 80
