name: Branch Name Convention Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Branch name rules
        uses: deepakputhraya/action-branch-name@v1.0.0
        with:
          regex: '(feature|bug|hotfix|release)\/(\w+-\d+-)?[\w-]+' # Allowed prefixes + optional JIRA ticket # + summary description
          allowed_prefixes: 'feature/,bug/,hotfix/,release/'
          ignore: master,main
          max_length: 80
