name: 'PR Title Convention Checks'

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Pull Request title rules
      uses: deepakputhraya/action-pr-title@v1.0.2
      with:
        regex: '(feat|fix)(\([a-zA-Z]+-[0-9]{1,}\))!?: .{10,80}' # Regex the title should match. E.g. feat(JIRA-1234): Title Proper
        allowed_prefixes: 'feat,fix' # title should start with the given prefix
        min_length: 10 # Min length of the title
        max_length: 80 # Max length of the title
